version: '3.9'

services:
  mc2-crud-test:
    image: ${DOCKER_REGISTRY:-mc}/mc2-crud-test:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "57870:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080