version: '3.9'

services:
  mc2-crud-test:
    container_name: mc2-crud-test
    build:
      context: .
      dockerfile: Mc2.CrudTest/Mc2.CrudTest.Presentation/Server/Dockerfile
    networks:
      - shared_network
    restart: always
    volumes:
      - ./Mc2.CrudTest/Mc2.CrudTest.Presentation/Server/appsettings.json:/app/appsettings.json  
networks:
  shared_network:
    external: true