version: '3.9'

services:
  mc2-crud-test:
    logging:
      options:
        max-size: 10m
    image: ${DOCKER_REGISTRY:-mc}/mc2-crud-test:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "7021:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      SQL_CONNECTION: ${PRODUCTION_SQL_CONNECTION}
      RABBIT_PASSWORD: ${PRODUCTION_RABBIT_PASSWORD}
      REDIS_PASSWORD: ${PRODUCTION_REDIS_PASSWORD}
      SALAMAT_TERMINAL_ID: ${PRODUCTION_SALAMAT_TERMINAL_ID}
      SALAMAT_MASTER_USERNAME: ${PRODUCTION_SALAMAT_MASTER_USERNAME}
      SALAMAT_MASTER_PASSWORD: ${PRODUCTION_SALAMAT_MASTER_PASSWORD}
      SALAMAT_CLIENT_IP_ADDRESS: ${PRODUCTION_SALAMAT_CLIENT_IP_ADDRESS}
      TAMIN_SOFTWARE_CLIENT_SECRET: ${PRODUCTION_TAMIN_SOFTWARE_CLIENT_SECRET}
      TAMIN_SOFTWARE_CLIENT_ID: ${PRODUCTION_TAMIN_SOFTWARE_CLIENT_ID}
      TZ: 'Asia/Tehran'
      PGTZ: 'Asia/Tehran'